#This is the configure file for NocSim
#You may create a new file for your own Routerless NoC

#The size of your NoC. Mesh topology is applied
#Please note that these two parameters must be even.
#We only use RLrec now, so mesh_dim_x and mesh_dim_y are the same
mesh_dim_x: 8
mesh_dim_y: 8

#The speed of injection of each node, expressed in flit per cycle per node
injection_rate: 0.2
#The number of flit per long packet
long_packet_size: 5
#The number of flit per short packet
short_packet_size: 1
#Method of size generation
#0-->generate size between short and long
#1-->only generate short and long, two size packet.
method_size_generator: 1

#If choosing 1 above, please fill ratio of short to long
short_ratio: 8
long_ratio: 2

#Ring configuration
#Algorithm used to generate the layout of the NoC
#Available algorithm:
#RLrec
ring_strategy: RLrec

#Strategy handling packets exceeding the buffer size
#Available strategy:
#Max--Use the max size of packet as buffer size. Isolated buffer
#Avg--Use average size of packet as buffer size. Isolated buffer
exb_strategy: Max
exb_num: 2

#Ejection settings
#The number of ejection port
ej_port_nu: 2
#Algorithm for multiple incoming packets
#Available algorithm:
#Oldest--Oldest packets have the highest priority
ej_strategy: Oldest

#Routing Selection Strategy
#Available algorithm:
#Shortest
#Secondwinner
routing_strategy: Shortest


#Traffic Generation
#Available traffic:
#Uniform
#Transpose
#BitReverse
#Hotspot
#SPLASH
#PARSEC
traffic_type: Uniform
#Only available when Hopspot is selected.
#Type Node_ID: weight
hotspot:
  2: 10
  10: 10
  18: 10
  26: 10
  34: 10
  40: 10
  48: 10
  56: 10

#Simulation parameters
#Period for run-time simulation, expressed in cycle
sim_time: 10000
#Period for warm-up, expressed in cycle
sim_warmup: 1000
#Output detailed information.
#1--Enable, Output Routing Information and Statistics of each node
#0--Disable
sim_detail: 0






  
