#This is the configure file for NocSim
#You may create a new file for your own Routerless NoC

#The size of your NoC. Mesh topology is applied
#Please note that these two parameters must be even.
#We only use RLrec now, so mesh_dim_x and mesh_dim_y are the same
mesh_dim_x: 8
mesh_dim_y: 8

#The speed of injection of each node, expressed in flit per cycle per node
injection_rate: 0.05
#The number of flit per long packet
long_packet_size: 5
#The number of flit per short packet
short_packet_size: 1
#Method of size generation
#0-->generate size between short and long
#1-->generate packet size with possibility
method_size_generator: 0

#Format:
#       packet size: possibility
#packet size and possibility must be integer
packet_ratio:
  5: 2
  1: 8



#Ring configuration
#Algorithm used to generate the layout of the NoC
#Available algorithm:
#RLrec
ring_strategy: RLrec

#Strategy handling packets exceeding the buffer size
#Available strategy:
#Max--Use the max size of packet as buffer size. Isolated buffer
#Avg--Use average size of packet as buffer size. Isolated buffer
exb_strategy: Max
exb_num: 1

#Ejection settings
#The number of ejection port
ej_port_nu: 2
#Algorithm for multiple incoming packets
#Available algorithm:
#Oldest--Oldest packets have the highest priority
ej_strategy: Oldest

#Routing Selection Strategy
#Available algorithm:
#Shortest
#Secondwinner
routing_strategy: Shortest


#Traffic Generation
#Available traffic:
#Uniform
#Transpose
#BitReverse
#Hotspot
traffic_type: Hotspot
#Only available when Hopspot is selected.
#Type Node_ID: weight
hotspot:
#This is the third column in 8*8 NoC
  3: 10
  11: 10
  19: 10
  27: 10
  35: 10
  43: 10
  54: 10
  63: 10

#Simulation parameters
#Period for run-time simulation, expressed in cycle
sim_time: 100000
#Period for warm-up, expressed in cycle
sim_warmup: 10000
#Output detailed information.
#1--Enable, Output Routing Information and Statistics of each node
#0--Disable
sim_detail: 1






  
