#This is the configure file for NocSim
#You may create a new file for your own routerless NoC

#The size of your NoC. Mesh topology is applied
#Please note that these two parameters must be even.
#We only use RLrec now, so mesh_dim_x and mesh_dim_y are the same
mesh_dim_x: 4
mesh_dim_y: 4

#The speed of injection of each node, expressed in packet per cycle per node
injection_rate: 0.01
#The number of flit per long packet
long_packet_size: 5
#The number of flit per short packet
short_packet_size: 1
#The size of one flit, expressed in bit
flit_size: 256
#Bandwidth between two nodes, expressed in bit
bandwidth: 256

#Ring configuration
#Algorithm used to generate the layout of the NoC
#Available algorithm:
#RLrec
ring_strategy: RLrec
#Physical limit for the number of rings across each node
ring_constraint: 6

#Extension Buffer of each node
#The size of each buffer in an exb pool, expressed in flit

#exb_size: 6

#The number of buffer in an exb pool

#exb_number: 5

#Strategy handling packets exceeding the buffer size
#Available strategy:
#Max--Use the max size of packet as buffer size. Isolated buffer
#Avg--Use average size of packet as buffer size. Isolated buffer
exb_strategy: Max
exb_num: 2

#Input port size configuration, measured by flit
in_port_size: 1

#Ejection settings
#The number of ejection port
ej_port_nu: 2
#Algorithm for multiple incoming packets
#Available algorithm:
#Oldest--Oldest packets have the highest priority
#Prio--Set different priority
ej_strategy: Oldest

#Routing Selection Strategy
#Available algorithm:
#Shortest
#Secondwinner
routing_strategy: Shortest


#Traffic Generation
#Available traffic:
#Uniform
#Transpose
#BitReverse
#Hotspot
#SPLASH
#PARSEC
traffic_type: Uniform
#Only available when Hopspot is selected.
#Type Node_ID: possibility
hotspot:
  2: 0.25
  5: 0.03

#Simulation parameters
#Period for run-time simulation, expressed in cycle
sim_time: 10000
#Period for warm-up, expressed in cycle
sim_warmup: 1000
#Simulation result type:
#Throughput--drain NoC when reaching run-time period. Some packets may not be injected, ejected or forwarded
#Latency--drain NoC until all ongoing packets have been ejected into nodes.
sim_type: Latency
#Latency type:
#Packet--average packet latency
#Flit--average flit latency
#Both--Packet+Flit
latency_type: both
#Value short packet to long packet
#Number of short packet/Number of long packet
#s_to_l:
#  short: 1
#  long: 1
#Output detailed information.
#1--Enable
#0--Disable
sim_detail: 0

#TODO
clock_period_ps: 200
reset_time: 10





  
